// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQvgGBfC8gIyFQZs5QmgJ2A_rlQEWUgUg',
    appId: '1:173038283040:web:7abbb6f2df4e0bbbdf0f45',
    messagingSenderId: '173038283040',
    projectId: 'projectmobile-25650',
    authDomain: 'projectmobile-25650.firebaseapp.com',
    storageBucket: 'projectmobile-25650.firebasestorage.app',
    measurementId: 'G-BTZ003LQ69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhs6A7LSjNLL6VHvgOBZmb8rVOyWkLHH0',
    appId: '1:173038283040:android:8e26e0a330ac0b86df0f45',
    messagingSenderId: '173038283040',
    projectId: 'projectmobile-25650',
    storageBucket: 'projectmobile-25650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDnp9LbM-HTGn1gxq-eiC5Ti8RcDzYd9U',
    appId: '1:173038283040:ios:2c3a77135efb9e3adf0f45',
    messagingSenderId: '173038283040',
    projectId: 'projectmobile-25650',
    storageBucket: 'projectmobile-25650.firebasestorage.app',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDnp9LbM-HTGn1gxq-eiC5Ti8RcDzYd9U',
    appId: '1:173038283040:ios:2c3a77135efb9e3adf0f45',
    messagingSenderId: '173038283040',
    projectId: 'projectmobile-25650',
    storageBucket: 'projectmobile-25650.firebasestorage.app',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQvgGBfC8gIyFQZs5QmgJ2A_rlQEWUgUg',
    appId: '1:173038283040:web:eee137d7367c16eddf0f45',
    messagingSenderId: '173038283040',
    projectId: 'projectmobile-25650',
    authDomain: 'projectmobile-25650.firebaseapp.com',
    storageBucket: 'projectmobile-25650.firebasestorage.app',
    measurementId: 'G-DDTHMN82SV',
  );
}
